### PR TITLE
Project level formatting

### PR DESCRIPTION
**Pull request by djgrant**
We had a lot of issues in js-exercises with PRs containing big diffs caused by different IDE formatting settings.

This adds project level settings via the `.vscode` folder and `editorconfig` (is that overkill if everyone is using VS Code?) for HTML, and `.prettierrc.js` for markdown and JS files (if we ever add them).

### CODE REVIEW

**Comment by rarmatei** [comment]
should we just install Prettier on everyone's VSCode from the beginning?

**Comment by djgrant** [comment]
Yes, absolutely. 

But there will always be exceptions who don't have prettier for whatever reason (contributors included)

**Comment by rarmatei** [comment]
Yes, very true. Maybe we can add this + a VSCode .extensions file, so when they get this project VSCode prompts everyone to install prettier?

That way we get live formatting as they save and work on files, and, if for some reason, somebody doesn't want to have prettier installed, we'll still format the files pre-commit as per your PR.

**Comment by NateWr** [comment]
Yes, please. Whatever will align things with the js exercises. I _think_ that the new machines may be loaded with our preferred editor config, but I'm not sure.

**Pull request closed without merging**
