### PR TITLE
completed exercises week 1&2 and week-3!

### PR DESCRIPTION
**Pull request by havvarslan**

### CODE REVIEW

**Comment by mattbryce93** [comment]
Week 1 Excercise 3: commit cd4387f1e5ee181feac58696f86ae849e22f80d6

Good effort on adding the time tag to the first message however the code you commited in the line.
`<span class="message__time">Mar 25, 2018 <time datetime="20:00"></time>7:25pm</span>`
References the incorrect time and doesn't include the date.
This line should have been:
` <span class="message__time">
            <time datetime="2018-03-25 19:25">Mar 25, 2018 7:25pm</time>
          </span>`
So as to notate the correct datetime. Good Effort Though!

**Comment by mattbryce93** [comment]
Week 1 Exercise 4: commit commit 8abb3c2dbd2a78ee97c379106bd27d5a26b23904

This exercise was an attempt to link in the css file so that we have some styling on the page. Unfortunately the page is not displaying properly here. The line of code you used was:
`<link rel="stylesheet" href="missing-styles.css" />`
This would have worked had the css file been in the same folder as your html file but it was actually in a subfolder called 'css'.

To access this css file the code required would be:
`<link rel="stylesheet" href="css/missing-styles.css" />`

You did do this correctly for the JavaScript so well done!

**Comment by mattbryce93** [comment]
Week 1 Exercise 6: commit d7a6e3f0d94f0ffc969d2c2db4f0b25ed1ac4fc7
 ```
.message--unread {
  border-style: solid;
  border-color: blue;
}
```
This css was close but ended up surrounding the entire message instead of the left side only, to only line the left side this would require:
```
.message--unread {
  border-left-color: blue;
  border-left-style: solid;
}
```
Good try though!

**Comment by mattbryce93** [comment]
Week 1 Exercise 7: commit 5e029f97e04b958076e9d180c607fb86951e4bfa
Good job on this one but the first task required you to only select the sentence 'All of your messages with Won are shown below.' to white. The css you wrote actually turned the footer test white also here is your code:
```
p {
  color: white;
  margin-bottom: 10px;
}
```
To make sure you only select the first sentence the code should have looked more like:
```
.site-header > p {
  color: white;
  margin-bottom: 10px;
}
```
This was also an issue with task 3:
'Use the Child Selector to change the text at the bottom that reads "Last message received Yesterday, 7:38pm.". Change the `font-size` to `12px` and use the `text-align` property to center the text.' 

In this one your code was:
```
.site-footer {
  font-size: 12px;
  text-align: center;
}
```
But to select the paragraph tag properly a Child Selector is required and should have looked more like:
```
.site-footer > p {
  font-size: 12px;
  text-align: center;
}
```
For task 4:
'Use the [:last-child Selector](https://learn.shayhowe.com/advanced-html-css/complex-selectors/#pseudo-classes) to change the last message in the list. Add a `box-shadow` of `4px 4px 0 #dba944` so that it stands out.'
The css you added was as follows:
```
.message--unread {
  box-shadow: 4px 4px 0 #dba944;
}
```
Which although it does add the box-shado to the correct message it was not with the [:last-child Selector] and should have been more like:
```
.messages div:last-child {
  box-shadow: 4px 4px 0 #dba944;
}
```
To allow the correct selector on the HTML div in the last message.

**Comment by mattbryce93** [comment]
Week 2 Exercise 11: commit 6e060e78f2be22a8158ed7f8ac25841cfd7fc4de
For this exercise the css you submitted was as follows:
```
.countries--first {
  display: flex;
  flex-direction: row-reverse;
}
```
This only got the first section to display correctly.
1. Open `flexbox.css` and write a CSS rule to apply `display: flex` to the "container" element. _Hint: The "container" element will be the parent element of each country._
This would have been done with:
```
.countries {
  display: flex;
}
```
The benefit of doing this is that it does display flex for all the containers at once. Coding like thi can help to keep your css files smaller and more maintainable.
2. Look at the First list of countries. Then look at the solution displayed to the side. Find the differences between the two lists.
This would have been done with:
```
.countries--first {
  flex-direction: row-reverse;
}
```
You got this but the difference is that I've split out the `display: flex` into one that will function for all the countries containers.

3. Use the property `flex-direction` to make the countries on the left look like the ones on the right.
This one would have been done with:
```
.countries--second {
  flex-direction: column;
}

.countries--third {
  flex-direction: column-reverse;
}
```
This is trickier as the second section was technically displaying correctly already but we want to add flex because we don't know what someone visiting the page will be viewing it with and we want our pages to work consistently across devices. The third section was actually in reverse order which is why we are reversing the column for that one.

**Comment by mattbryce93** [comment]
Week 2 Exercise 12: commit 6e060e78f2be22a8158ed7f8ac25841cfd7fc4de
The css you submitted was:
```
.countries--second {
  display: flex;
  flex-direction: flex-end;
  justify-content: space-between;
}
.countries--first {
  display: flex;
  flex-direction: flex-end;
  justify-content: flex-end;
}
.countries--third {
  display: flex;
  flex-direction: flex-end;
  justify-content: flex-end;
}
```
This css had a couple of issues. But it was really close so you should feel good about that :) The issues we had I've mentioned before, the css at the top of the file did a few things:
```
.countries {
  display: flex;
}

.countries--second .country {
  padding: 0.5em;
}
```
In Particular it turned all the countries containers into `display: flex` so typing that into each the sections isn't needed as it has already been done with the first `.countries` selector. The other issue was that `flex-end` is not a valid option for `flex-direction` you have `row, row-reverse, column and column-reverse` available for `flex-direction`. The code below would have been how I would have answered. Good job though!
```
.countries--first {
  flex-direction: row;
  justify-content: flex-end;
}

.countries--second {
  flex-direction: row;
  justify-content: space-between;
}

.countries--third {
  flex-direction: column;
  justify-content: flex-end;
}
```

**Comment by mattbryce93** [comment]
Perfect, the rest of your exercises were great, well done Havva!

**Comment by havvarslan** [comment]
I have added week-3 exercises (19-26) committed together, 28&29 separately.

**Pull request closed without merging**
